In [ ]:
!pip install anonypy

Requirement already satisfied: anonypy in /usr/local/lib/python3.11/dist-packages (0.2.1)

In [ ]:
#Attribute require libraries
## Acknowledgements

# This project uses the following libraries:
# - AnonyPy(https://github.com/glassonion1/anonypy) by Taisuke Fujita â€” licensed under MIT License.

In [ ]:
#import required libraries
import anonypy
import pandas as pd

In [ ]:
data = pd.read_csv("adult.csv")
data.columns = data.columns.str.strip()

cols = set(("workclass", "education", "marital.status", "occupation", "sex", "native.country"))
for col in cols:
    data[col] = data[col].astype("category")

In [ ]:
quasi_identifiers = ["age", "education", "marital.status", "occupation", "native.country"]
sensitive_attributes = "income"

In [ ]:
p = anonypy.Preserver(data, quasi_identifiers, sensitive_attributes)
rows = p.anonymize_k_anonymity(k=10)

dfn = pd.DataFrame(rows)
dfn.head()

,age,education,marital.status,occupation,native.country,income,count
0,[18-36],"[Doctorate,10th,12th,Prof-school,Preschool,7th...","[Never-married,Divorced]","[Sales,Prof-specialty,Other-service,Handlers-c...","[Nicaragua,Taiwan,Honduras,Puerto-Rico,Hong,Ja...",<=50K,18
1,[18-36],"[Doctorate,10th,12th,Prof-school,Preschool,7th...","[Never-married,Divorced]","[Sales,Prof-specialty,Other-service,Handlers-c...","[Nicaragua,Taiwan,Honduras,Puerto-Rico,Hong,Ja...",>50K,1
2,[22-36],"[Assoc-voc,1st-4th,Masters,Assoc-acdm]","[Never-married,Divorced]","[?,Adm-clerical,Priv-house-serv,Transport-moving]","[Poland,France,Jamaica,Guatemala,Haiti,Japan,I...",<=50K,11
3,[21-35],"[Assoc-acdm,1st-4th,11th,Assoc-voc]","[Married-civ-spouse,Married-spouse-absent]","[Adm-clerical,Other-service,Exec-managerial,Ma...","[Honduras,England,Thailand,Guatemala,Haiti,Vie...",<=50K,10
4,[21-35],"[Assoc-acdm,1st-4th,11th,Assoc-voc]","[Married-civ-spouse,Married-spouse-absent]","[Adm-clerical,Other-service,Exec-managerial,Ma...","[Honduras,England,Thailand,Guatemala,Haiti,Vie...",>50K,1